filebeat.inputs:
- type: container
  paths:
    - '/var/lib/docker/containers/*/*.log'
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: log

processors:
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - add_host_metadata: ~
  - decode_json_fields:
      fields: ["message"]
      target: ""
      overwrite_keys: true
  - drop_fields:
      fields: ["log", "stream", "input_type", "offset", "prospector"]
  # Anonymisation des données sensibles
  - script:
      lang: javascript
      source: >
        function process(event) {
          var message = event.Get("message");
          if (message) {
            // Masquer les numéros de sécurité sociale
            message = message.replace(/\d{13,15}/g, "[NUMÉRO SÉCURITÉ SOCIALE MASQUÉ]");
            // Masquer les emails
            message = message.replace(/\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}\b/g, "[EMAIL MASQUÉ]");
            event.Put("message", message);
          }
          return event;
        }

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644
